apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: get-started
  name: helloworld-controller-2
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: get-started
  type: NodePort
status:
  loadBalancer: {}
